spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/kopring
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
